
server:
  port: 8071
  servlet:
    context-path: /dev-api

spring:
  cache:
    ehcache:
      config: classpath:configs/ehcache.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/youlai_boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  resources:
    static-locations: classpath:/frontend/,classpath:/static/,classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:com/newsupplytech/nstdevbase/mapper/xml/*Mapper.xml
  type-aliases-package: com.newsupplytech.nstdevbase.model
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.newsupplytech.nstdevbase.modules.mapper: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
